 var firebaseConfig = {
    apiKey: "AIzaSyDjkNh6-DGp5UhRsQxIjqMdfZCY7kDue3U",
    authDomain: "tech-bud.firebaseapp.com",
    databaseURL: "https://tech-bud.firebaseio.com",
    projectId: "tech-bud",
    storageBucket: "tech-bud.appspot.com",
    messagingSenderId: "1024766291978",
    appId: "1:1024766291978:web:4e4d377b835e8c06"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);

 

  var encrypted1 = CryptoJS.AES.encrypt("+919427218654", "enanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbookIthassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangedItwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassagesndmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsumWhydoweuseitItisalongestablishedfactthatareaderwillbedistractedbythereadablecontentofapagewhenlookingatitslayoutThepointofusingLoremIpsumisthatithasamorelessnormaldistributionoflettersasopposedtousingContentherecontentheremakingitlooklikereadableEnglishManydesktoppublishingpackagesanwebpageeditorsnowuseLoremIpsumastheirdefaultmodeltextandasearchforloremipsumwilluncovermanywebsitesstillintheirinfancyVariousversionshaveevolvedovertheyearssometimesbyaccidentsometimesonpurposeinjectedhumourandthelikeWheredoesitcomefromContrarytopopularbelieforemIpsumisnotsimplyrandomtextIthasrootsinapieceofclassicalLatinliteraturefrom45BCmakingitover2000yearsoldRichardMcClintockaLatinprofessoratHampdenydneyCollegeinVirginialookeduponeofthemoreobscureLatinwordsconsecteturfromaLoremIpsumpassageandgoingthroughthecitesofthewordinclassicalliteraturediscoveredtheundoubtables");
        var decrypted1 = CryptoJS.AES.decrypt(encrypted1, "enanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbookIthassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangedItwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassagesndmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsumWhydoweuseitItisalongestablishedfactthatareaderwillbedistractedbythereadablecontentofapagewhenlookingatitslayoutThepointofusingLoremIpsumisthatithasamorelessnormaldistributionoflettersasopposedtousingContentherecontentheremakingitlooklikereadableEnglishManydesktoppublishingpackagesanwebpageeditorsnowuseLoremIpsumastheirdefaultmodeltextandasearchforloremipsumwilluncovermanywebsitesstillintheirinfancyVariousversionshaveevolvedovertheyearssometimesbyaccidentsometimesonpurposeinjectedhumourandthelikeWheredoesitcomefromContrarytopopularbelieforemIpsumisnotsimplyrandomtextIthasrootsinapieceofclassicalLatinliteraturefrom45BCmakingitover2000yearsoldRichardMcClintockaLatinprofessoratHampdenydneyCollegeinVirginialookeduponeofthemoreobscureLatinwordsconsecteturfromaLoremIpsumpassageandgoingthroughthecitesofthewordinclassicalliteraturediscoveredtheundoubtables");